### ISSUE TITLE
Can textButtonStyle accept a color conditional?

### ISSUE THREAD

**Issue by rjbdallas** [rarenatoe/more-or-less#4] opened 2023-06-24 17:07 UTC
THANK YOU FOR A HANDY PACKAGE -- 
I am writing a React Native/Expo app that has Light/Dark mode triggered by an icon onPress. 

Can textButtonStyle accept a conditional?
When clicking onPress action button on the page, the MoreOrLess section resets to initial state (collapsed).

Case: User Bio TEXT on screen is black when in Light mode and the "MORE" text is the color I set -- Blue.
Pushing the onPress Light/Dark Mode icon -- 
MoreOrLess section resets back to collapsed
User Bio TEXT is black (expected white)
"MORE" text is white (expected white)
Pressing "MORE" -- 
Text section expands -- text is black (expected white)
"LESS" text is white (expected white)

Here is the code -- I only included specific sections of the code:

` 
import { MoreOrLess } from "@rntext/more-or-less";
import CustomText from "./CustomText"; {/* From your example */}
import {useColorScheme} from "nativewind";
import {MaterialCommunityIcons} from '@expo/vector-icons';

const ProfilePage = () => {

const {colorScheme, toggleColorScheme} = useColorScheme();

return (

<MaterialCommunityIcons name="theme-light-dark" size={36} color="white"
                                                onPress={() => toggleColorScheme(colorScheme === "light" ? "dark" : "light")}/>

<MoreOrLess
                        numberOfLines={1}
                        textComponent={CustomText}
                        textButtonStyle={{ color: colorScheme === 'dark' ? 'white' : 'black' }}
                        animated
                    >
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
                    </MoreOrLess>

);

};

export default ProfilePage

`

Any help would be appreciated.
Thanks

**Comment by rarenatoe** [comment] 2023-06-25 03:46
Hi, I tried to reproduce your issue, but I am having trouble encountering it.
I am able to update the text color of the text button on the press of an outside button. Also I am able to expand it and collapse it without anything changing.

Here is an example code
```ts
export default function App() {
  const [theme, setTheme] = React.useState<'light' | 'dark'>('light');

  return (
    <View style={styles.appContainer}>
      <Button
        title="Hola"
        onPress={() => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'))}
      />
      <View style={styles.container} />
      <View style={[styles.container, styles.center]}>
        <MoreOrLess
          containerStyle={styles.textContainer}
          numberOfLines={5}
          textComponent={CustomText}
          textStyle={styles.text}
          textButtonStyle={theme === 'light' ? styles.textButton : { color: 'yellow' }}
          animated
        >
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
          been the industry's standard dummy text ever since the 1500s, when an unknown printer took
          a galley of type and scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting, remaining essentially
          unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
          Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
          PageMaker including versions of Lorem.
        </MoreOrLess>
      </View>
      <View style={styles.container} />
    </View>
  );
}
```

Example video on android:

https://github.com/rarenatoe/more-or-less/assets/44821537/e3177c2b-08e8-411a-873e-476b0b2ad982

**Could you give me an actual reproduceable example?**

**Comment by rarenatoe** [comment] 2023-07-03 02:39
closing due to being unable to reproduce.

**Closed by rarenatoe** 2023-07-03 02:39 UTC
